[build]
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "16.20.0"

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

# Prerender specific routes
[[redirects]]
from = "/events"
to = "/events"
status = 200
force = true

[redirects.headers]
X-Robots-Tag = "all"
cache-control = "public, max-age=0, must-revalidate"

# SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
